### ISSUE TITLE
Cannot install via pip

### ISSUE THREAD

**Issue by mohd-akram** [reddit/baseplate.py#181]
Using pip 10.0.1 and python 3.6, `pip install baseplate` returns:

```
running bdist_wheel
running build
running build_py
SPECIAL baseplate/thrift/baseplate.thrift build/thrift/baseplate/thrift/baseplate.thrift_buildstamp
mkdir -p build/thrift/baseplate/thrift/baseplate.thrift
thrift1 -strict -gen py:utf8strings,slots,new_style -out build/thrift/baseplate/thrift/baseplate.thrift baseplate/thrift/baseplate.thrift
cp -r build/thrift/baseplate/thrift/baseplate.thrift/baseplate/thrift/ baseplate/
touch build/thrift/baseplate/thrift/baseplate.thrift_buildstamp
make: *** No rule to make target `tests/integration/test.thrift', needed by `build/thrift/tests/integration/test.thrift_buildstamp'.  Stop.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/var/folders/5k/h40qktzn2dl9z13v0cmf33hh0000gn/T/pip-install-o4ua71_c/baseplate/setup.py", line 125, in <module>
    'build_py': BuildPyCommand,
  File "/Users/mohamed/.virtualenvs/local/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/mohamed/.virtualenvs/local/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 179, in run
    self.run_command('build')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/private/var/folders/5k/h40qktzn2dl9z13v0cmf33hh0000gn/T/pip-install-o4ua71_c/baseplate/setup.py", line 67, in run
    self._make_thrift()
  File "/private/var/folders/5k/h40qktzn2dl9z13v0cmf33hh0000gn/T/pip-install-o4ua71_c/baseplate/setup.py", line 64, in _make_thrift
    subprocess.check_call(make_cmd)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/make', 'thrift']' returned non-zero exit status 2.

----------------------------------------
Failed building wheel for baseplate
```

It seems the `tests` directory is missing from the tarball uploaded to PyPI.

**Comment by cshoe** [comment]
Hey @mohd-akram,

Currently, there's a hard install requirement on having a Thirft compiler available. There's [some work](https://github.com/reddit/baseplate/pull/195) happening to remove that requirement from the install process but it'll be some time.

In the meantime, you can install the `fbthrift-compiler` and `python3-fbthrift` (or `python-fbthrift` if you're on Python 2) system packages.

**Comment by mohd-akram** [comment]
I do have a Thrift compiler installed and can install the package using the git repo. The problem seems to be that some files, namely the `tests` directory, are missing from the PyPI distribution:

    make: *** No rule to make target `tests/integration/test.thrift', needed by `build/thrift/tests/integration/test.thrift_buildstamp'.  Stop.

This can be fixed by either [not excluding the `tests` directory](https://github.com/reddit/baseplate/blob/3fd8bd0cb8aa4a10271aa5f78bdc85ebf02e6730/setup.py#L81) or by changing the [`thrift` rule](https://github.com/reddit/baseplate/blob/3fd8bd0cb8aa4a10271aa5f78bdc85ebf02e6730/Makefile#L9) in the Makefile or adding another one that doesn't build tests since it's used in [`setup.py`](https://github.com/reddit/baseplate/blob/3fd8bd0cb8aa4a10271aa5f78bdc85ebf02e6730/setup.py#L63).

**Comment by spladug** [comment]
Pre-built wheels are published to PyPI now so this should work.
