### ISSUE TITLE
Ensure baseplate-script's new argument stuff is backwards compatible within reason

### ISSUE THREAD

**Issue by spladug** [reddit/baseplate.py#347]
This example worked before but now doesn't:

```console
$ baseplate-script example.ini foo.models.cql:create_schema --app-name bar
Traceback (most recent call last):
  File "/usr/local/bin/baseplate-script", line 14, in <module>
    load_and_run_script()
  File "/usr/local/lib/python3.7/dist-packages/baseplate/server/__init__.py", line 281, in load_and_run_script
    if _fn_accepts_additional_args(args.entrypoint, args.args):
  File "/usr/local/lib/python3.7/dist-packages/baseplate/server/__init__.py", line 307, in _fn_accepts_additional_args
    "script function does not accept additional arguments, "
ValueError: script function does not accept additional arguments, but additional arguments were provided
```

**Comment by spladug** [comment]
Fixed by @bradengroom in #349
